language: python
sudo: false
python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7
  - 3.8

install:
  - pip install coveralls
script:
  - coverage run --source=fittotcx setup.py test
  - python setup.py install
  - python setup.py test
  - fittotcx tests/test.fit > /dev/null
after_success:
  - coveralls
